# Generated by Django 2.2 on 2020-04-26 02:27

import appdjango.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.TextField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=1, max_digits=5)),
                ('foto_articulo', models.ImageField(upload_to=appdjango.models.url_articulo)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField()),
                ('direccion_envio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapago', models.DateField()),
                ('detallepago', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=35)),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('fk_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdjango.Articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='fk_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdjango.Vendedor'),
        ),
    ]
